// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-696bFRBpkhv5aOc11BDbAKZC3HP0su0',
    appId: '1:339863148977:web:27d1c9b255efb56d688590',
    messagingSenderId: '339863148977',
    projectId: 'byme-12aeb',
    authDomain: 'byme-12aeb.firebaseapp.com',
    storageBucket: 'byme-12aeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo46Hn3OeC9yBLAT6QDNDOGrZh6qEE4n4',
    appId: '1:339863148977:android:b3c9ffd16164ca35688590',
    messagingSenderId: '339863148977',
    projectId: 'byme-12aeb',
    storageBucket: 'byme-12aeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRkaA2ibsdFB5JyvLDsFN0prQY7qax6NA',
    appId: '1:339863148977:ios:768a31a03e9bed46688590',
    messagingSenderId: '339863148977',
    projectId: 'byme-12aeb',
    storageBucket: 'byme-12aeb.appspot.com',
    iosBundleId: 'com.example.firestoreAppTi43',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRkaA2ibsdFB5JyvLDsFN0prQY7qax6NA',
    appId: '1:339863148977:ios:956f220a1b3f0ae6688590',
    messagingSenderId: '339863148977',
    projectId: 'byme-12aeb',
    storageBucket: 'byme-12aeb.appspot.com',
    iosBundleId: 'com.example.firestoreAppTi43.RunnerTests',
  );
}
